<?php
/** @var \Mirasvit\Profiler\Block\Tab\Code $block */

use Magento\Framework\Profiler\Driver\Standard\Stat;
use Mirasvit\Profiler\Profile\General;

$dump = $block->getCodeDump();
$general = $block->getGeneralDump();

/** @var \Mirasvit\Profiler\Helper\Format $format */
$format = $this->helper('Mirasvit\Profiler\Helper\Format');
?>
<div class="metric">
    <strong><?= $format->formatTime($general[General::EXECUTION_TIME]) ?> ms</strong>
    <i>Total Time</i>
</div>
<div class="metric">
    <strong><?= $format->formatTime($general[General::DB_TIME]) ?> ms</strong>
    <i>Database Time</i>
</div>

<table id="profiler-table" data-threshold="#profiler-table-threshold">
    <thead>
    <tr>
        <th>Timer</th>
        <th>Time <sup>ms</sup></th>
        <th>Avg Time <sup>ms</sup></th>
        <th>Count</th>
    </tr>
    </thead>
    <tbody>
    <?php $idx = 0 ?>
    <?php foreach ($dump as $timerId => $item): ?>
        <tr data-tt-id="<?= $timerId ?>" data-tt-parent-id="<?= $block->getParentTimerId($timerId) ?>"
            data-threshold-value="<?= $item[Stat::TIME] * 1000 ?>">
            <td>
                <?php for ($i = 0; $i < $block->getLevel($timerId); $i++): ?>
                    <?= str_repeat('·', 10) ?>&nbsp;
                <?php endfor ?>
                <?= $block->renderTimerId($timerId) ?>
            </td>
            <td class="text-right">
                <?= $format->formatTime($item[Stat::TIME], true) ?>
                <div class="timer-line" style="width: <?= $block->getTimerLength($timerId) ?>%;"></div>
            </td>
            <td class="text-right">
                <?= $format->formatTime($item[Stat::TIME] / $item[Stat::COUNT], true) ?>
            </td>
            <td class="text-right"><?= $item[Stat::COUNT] ?></td>
        </tr>
    <?php endforeach ?>
    </tbody>
</table>
<script>
    //    require([
    //        'jquery',
    //        'Mirasvit_Profiler/js/table'
    //    ], function ($) {
    //        $('#profiler-table').profilerTable({});
    //    });
</script>