<?php
/** @var \Mirasvit\Profiler\Block\Tab\Database $block */
use Mirasvit\Profiler\Profile\Database;

$dump = $block->getDump();

/** @var \Mirasvit\Profiler\Helper\Format $format */
$format = $this->helper('Mirasvit\Profiler\Helper\Format');
?>
<div class="metric">
    <strong><?= $format->formatTime($dump[Database::TOTAL_ELAPSED]) ?> ms</strong>
    <i>Total Queries Time</i>
</div>
<div class="metric">
    <strong><?= $dump[Database::TOTAL_QUERIES] ?></strong>
    <i>Total Queries</i>
</div>


<div class="mst-threshold" id="sql-table-threshold">
    <div class="value"></div>
</div>

<?php $idx = 0 ?>
<table id="sql-table" data-threshold="#sql-table-threshold">
    <thead>
    <tr>
        <th>#</th>
        <th>Query Occurance</th>
        <th>Time <sup>ms</sup></th>
        <th>SQL Query</th>
        <th>Query Params</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($dump['profiles'] as $query): ?>
        <tr data-threshold-value="<?= $query[Database::QUERY_ELAPSED] ?>">
            <td class="text-right"><?= ++$idx ?></td>
            <td><?= $query[Database::QUERY_COUNT] ?? 'N/A' ?></td>
            <td class="text-right">
                <?= $format->formatTime($query[Database::QUERY_ELAPSED]) ?>
            </td>
            <td><?= \SqlFormatter::format($query[Database::QUERY]) ?></td>
            <td><?= $format->any($query[Database::QUERY_PARAMS]) ?></td>
        </tr>
    <?php endforeach ?>
    </tbody>
</table>

<script>
    $(function () {
        $("#sql-table").tablesorter();
    });
</script>