<?php
/** @var \Mirasvit\Profiler\Block\Tab\Profiler $block */

$stat = $block->getStat();

/** @var \Mirasvit\Profiler\Helper\Format $format */
$format = $this->helper('Mirasvit\Profiler\Helper\Format');
?>
<div class="mst-threshold" id="profiler-table-threshold">
    <div class="value"></div>
</div>

<table id="profiler-table" class="wide" data-threshold="#profiler-table-threshold">
    <thead>
    <tr>
        <th><?= __('Timer Id') ?></th>
        <th><?= __('Time (ms)') ?></th>
        <th><?= __('Avg (ms)') ?></th>
        <th><?= __('Cnt') ?></th>
    </tr>
    </thead>
    <tbody>
    <?php $idx = 0 ?>
    <?php foreach ($stat->getFilteredTimerIds() as $timerId): ?>
        <tr data-tt-id="<?= $timerId ?>" data-tt-parent-id="<?= $this->getParentTimerId($timerId) ?>"
            data-threshold-value="<?= $stat->fetch($timerId, 'sum') * 1000 ?>">
            <td>
                <?= $this->renderTimerId($stat->fetch($timerId, 'id')) ?>
            </td>
            <td class="number">
                <?= $format->formatTime($stat->fetch($timerId, 'sum')) ?>
                <div class="timer-line" style="width: <?= $block->getTimerLength($timerId) ?>%;"></div>
            </td>
            <td class="number"><?= $format->formatTime($stat->fetch($timerId, 'avg')) ?></td>
            <td class="number"><?= $stat->fetch($timerId, 'count') ?></td>
        </tr>
    <?php endforeach ?>
    </tbody>
</table>
<script>
    require([
        'jquery',
        'Mirasvit_Profiler/js/table'
    ], function ($) {
        $('#profiler-table').profilerTable({});
    });
</script>