<?php
/** @var \Mirasvit\Profiler\Block\Tab\Sql $block */

$profiler = $block->getDbProfiler();
$totalTime = $profiler->getTotalElapsedSecs();
$slowQueries = $block->getSlowQueries();

/** @var \Mirasvit\Profiler\Helper\Format $format */
$format = $this->helper('Mirasvit\Profiler\Helper\Format');

?>
<table cellpadding="0" cellspacing="0">
    <tr>
        <th><?= __('Total Time') ?></th>
        <td><?= $format->formatTime($totalTime) ?> ms</td>
    </tr>
    <tr>
        <th><?= __('Total Queries') ?></th>
        <td><?= $profiler->getTotalNumQueries() ?></td>
    </tr>
</table>

<div class="mirasvit-prifiler-tab-sql__timeline">
    <?php /** @var $query Zend_Db_Profiler_Query */ ?>
    <?php foreach ($profiler->getQueryProfiles() as $query): ?>
        <div style="width: <?= ($query->getElapsedSecs() / $profiler->getTotalElapsedSecs() * 100) ?>%"></div>
    <?php endforeach ?>
</div>

<h3>Slow Queries</h3>

<table cellpadding="0" cellspacing="0" class="wide">
    <tr>
        <th><?= __('SQL Query') ?></th>
        <th><?= __('Time (ms)') ?></th>
        <th>%</th>
    </tr>
    <?php foreach ($slowQueries as $queryId => $time): ?>
        <?php $query = $profiler->getQueryProfile($queryId) ?>
        <tr>
            <td><?= \SqlFormatter::format($query->getQuery()) ?></td>
            <td class="number"><?= $format->formatTime($time) ?></td>
            <td class="number"><?= round($time / $totalTime * 100, 1) ?>%</td>
        </tr>
    <?php endforeach ?>
</table>

<h3>All Queries</h3>

<?php $idx = 0 ?>
<table cellpadding="0" cellspacing="0" class="wide">
    <tr>
        <th>#</th>
        <th>Time (ms)</th>
        <th>SQL Query</th>
        <th>Query Params</th>
    </tr>
    <?php foreach ($profiler->getQueryProfiles() as $query): ?>
        <tr>
            <td class="number"><?= ++$idx ?></td>
            <td class="number"><?= $format->formatTime($query->getElapsedSecs()) ?></td>
            <td><?= \SqlFormatter::format($query->getQuery()) ?></td>
            <td><?= json_encode($query->getQueryParams()) ?></td>
        </tr>
    <?php endforeach ?>
</table>
