<?php
/** @var \Mirasvit\Profiler\Block\Tab\Sql $block */

$dump = $block->getDump();

/** @var \Mirasvit\Profiler\Helper\Format $format */
$format = $this->helper('Mirasvit\Profiler\Helper\Format');
?>
<div class="metric">
    <strong><?= $format->formatTime($dump['totalElapsedSecs']) ?> ms</strong>
    <i>Total Time</i>
</div>
<div class="metric">
    <strong><?= $dump['totalNumQueries'] ?></strong>
    <i>Total Queries</i>
</div>


<div class="mst-threshold" id="sql-table-threshold">
    <div class="value"></div>
</div>

<?php $idx = 0 ?>
<table id="sql-table" data-threshold="#sql-table-threshold">
    <tr>
        <th>#</th>
        <th>Time (ms)</th>
        <th>SQL Query</th>
        <th>Query Params</th>
    </tr>

    <?php foreach ($dump['profiles'] as $query): ?>
        <tr data-threshold-value="<?= $query['elapsedSecs'] * 1000 ?>">
            <td class="number"><?= ++$idx ?></td>
            <td class="number"><?= $format->formatTime($query['elapsedSecs']) ?></td>
            <td><?= \SqlFormatter::format($query['query']) ?></td>
            <td><?= json_encode($query['queryParams']) ?></td>
        </tr>
    <?php endforeach ?>
</table>

<script>
    //    require([
    //        'jquery',
    //        'Mirasvit_Profiler/js/table'
    //    ], function ($) {
    //        $('#sql-table').profilerTable({});
    //    });
</script>