<?php
/** @var \Mirasvit\Profiler\Block\Container $block */

?>
<style>
    <?= $block->getStyles() ?>
</style>

<div class="mst-profiler-clearfix"></div>

<div class="mst-profiler__container">
    <div class="mst-profiler__container-toolbar">
        <ul class="mst-profiler__container-tabs" data-role="profiler-tabs">
            <?php foreach ($block->getTabs() as $key => $tab): ?>
                <li data-tab="<?= $key ?>">
                    <?= $tab->getLabel() ?>
                </li>
            <?php endforeach ?>
        </ul>

        <div class="mst-profiler__container-info">
            <div class="mst-profiler__container-info-item">
                <small><?= $_SERVER['REMOTE_ADDR'] ?></small>
            </div>
            <div class="mst-profiler__container-info-item">
                <i class="fa fa-fw fa-clock-o"></i>
                <?= round($block->getRequestTime() * 1000, 1) ?> ms
            </div>

            <div class="mst-profiler__container-info-item">
                <i class="fa fa-fw fa-database"></i>
                <?= $block->getDbTotalNumQueries() ?> in <?= round($block->getDbTotalElapsedSecs() * 1000, 1) ?> ms
            </div>
        </div>
    </div>

    <?php foreach ($this->getTabs() as $key => $tab): ?>
        <div class="mst-profiler__container-tab-content" data-tab-content="<?= $key ?>">
            <?= $tab->toHtml() ?>
        </div>
    <?php endforeach ?>
</div>

<script>
    require([
        'jquery'
    ], function ($) {
        $('[data-role=profiler-tabs] li').on('click', function (e) {
            $('[data-role=profiler-tabs] li').removeClass('_active');
            $(e.currentTarget).addClass('_active');
            $('[data-tab-content]').hide();
            $('[data-tab-content=' + $(e.currentTarget).attr('data-tab') + ']').show();
        });

        $('[data-role=profiler-tabs] li:first').click();
    });
</script>