<?php
/** @var \Mirasvit\Profiler\Block\Iframe $block */

?>
<iframe class="mst-profiler__iframe"
        src="<?= $block->getUrl('profiler/profile/view', ['id' => $this->getProfileId()]) ?>"></iframe>
<script>
    function handlingMsg(e) {
        jQuery('.mst-profiler__iframe').css('height', e.data);
    }
    addEventListener("message", handlingMsg, true);
</script>
<style>
    .mst-profiler__iframe {
        width: 100%;
        border: 2px solid #514943;
        min-height: 300px;
    }
</style>