<!doctype html>
<html>
<head>
    <script src="//code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.28.15/js/jquery.tablesorter.min.js"></script>
    <link rel="stylesheet" href="<? echo $this->getViewFileUrl('Mirasvit_Profiler::css/module.css')?>">
</head>
<body>
<?= $layoutContent ?>
<script>
    $(function () {
        setInterval(function () {
            parent.postMessage($('body').height(), '*');
        }, 1000);
    })
</script>
</body>
</html>
