<?php
/** @var \Mirasvit\Profiler\Block\Profile\Listing $block */

use Mirasvit\Profiler\Profile\Meta;

/** @var \Mirasvit\Profiler\Helper\Format $format */
$format = $this->helper('Mirasvit\Profiler\Helper\Format');
?>
<table>
    <tr>
        <th></th>
        <th>Status</th>
        <th>Method</th>
        <th>Time</th>
        <th>Execution <sup>ms</sup></th>
        <th>URL</th>
    </tr>
    <?php foreach ($block->getList() as $item): ?>
        <tr>
            <td class="text-center">
                <a href="<?= $block->getUrl('profiler/profile/view', ['id' => $item['ID']]) ?>">
                    view
                </a>
            </td>
            <td class="text-center"><?= $item[Meta::RESPONSE_CODE] ?></td>
            <td class="text-center"><?= $item[Meta::METHOD] ?></td>
            <td nowrap="nowrap"><?= date('M d, H:i:s', $item[Meta::TIME]) ?></td>
            <td nowrap="nowrap" class="text-right"><?= $format->formatTime($item[Meta::EXECUTION_TIME]) ?></td>
            <td><?= $item[Meta::URL] ?></td>
        </tr>
    <?php endforeach ?>
</table>